define(['qlik', 'jquery', './config', 'util', 'enigma', 'autogenerated/qix/engine-api', 'text!./style.css'],

  function (qlik, $, config, Util, enigma, schema, style) {
    console.log(enigma);
    _this = this;

    var global = qlik.getGlobal();
    var app = qlik.currApp(_this);

    var cfg = {
      schema: schema,
      appId: app.model.layout.qFileName,
      session: {
        host: Util.hostname,
        port: Util.port || undefined,
        prefix: Util.basePath,
        unsecure: !Util.isSecure,
        reloadURI: Util.reloadURI
      }
    };


    $('<style>').html(style).appendTo('head');

    return {
      definition: config.definition,
      initialProperties: config.initialProperties,
      paint: main
    };

    function main($element, layout) {

      var qId = 'BM01';
      var qType = 'Bookmark';

      $element.empty();
      $element.append(

        $('<button>Create Bookmark</button>').click(function () {

          var bookmarkProperties = { "qInfo": { "qId": qId, "qType": qType } };

          enigma.getService('qix', cfg).then((qix) => {

            qix.app.destroyBookmark(qId).then((layout) => {
               console.log(layout);
              qix.app.createBookmark(bookmarkProperties).then((layout) => {
                console.log(layout);
                
                var isPersonalMode;
                global.isPersonalMode(function (reply) {
                  isPersonalMode = reply.qReturn;
                  if (isPersonalMode) {
                    console.log('Personal Mode!');
                    qix.app.doSave();
                  }
                });
              });
            });
          });
        })
      );

      $element.append(

        $('<button style="margin-left:10px">Apply Bookmark</button>').click(function () {

          enigma.getService('qix', cfg).then((qix) => {
            qix.app.applyBookmark(qId).then((layout) => {
              console.log(layout);
            });
          });
        })
      );

      $element.append(

        $('<button style="margin-left:10px">Get Bookmark</button>').click(function () {

          enigma.getService('qix', cfg).then((qix) => {
            qix.app.getBookmark(qId).then((bookmark) => {
              bookmark.getLayout().then((layout) => {
                console.log(layout);
              });
            });
          });
        })
      );

    }
  });




